version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: uruhongore_dt
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: E3c6j8b1s32
      POSTGRES_DB: uruhongore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: